- .travis.yml
- Gemfile
- gemfiles/Gemfile.rails-4.2
- gemfiles/Gemfile.rails-5.0
- gemfiles/Gemfile.rails-5.1
- gemfiles/Gemfile.rails-5.2
- gemfiles/Gemfile.rails-6.0
- gemfiles/Gemfile.rails-master
- lib/parsers/wallaby/parser.rb
- lib/wallaby/core.rb
- spec/dummy/config/application.rb
- spec/dummy/config/environments/development.rb
- spec/dummy/config/environments/production.rb
- spec/dummy/config/environments/test.rb
- spec/dummy/config/initializers/assets.rb
- spec/parsers/wallaby/parser_spec.rb
- spec/rails_helper.rb
- wallaby-core.gemspec
Change parse to recognise basic data types, such as null, boolean integer and string
> feat: handle basic data type for colon query

- .travis.yml
- CHANGELOG.md
- README.md
- lib/wallaby/core/version.rb
- wallaby-core.gemspec
New version 0.2.0 and document update
> chore: new version 0.2.0

- CHANGELOG.md
- lib/wallaby/core/version.rb
> chore: ready for 0.2.1

- lib/authorizers/wallaby/cancancan_authorization_provider.rb
- lib/concerns/wallaby/application_concern.rb
- lib/concerns/wallaby/authentication_concern.rb
- lib/concerns/wallaby/resources_concern.rb
- lib/helpers/wallaby/resources_helper.rb
- lib/helpers/wallaby/secure_helper.rb
- lib/utils/wallaby/logger.rb
- lib/utils/wallaby/utils.rb
- lib/wallaby/configuration/security.rb
- lib/wallaby/core.rb
- spec/concerns/wallaby/authentication_concern_spec.rb
- spec/dummy/db/postgresql_schema.rb
- spec/services/wallaby/sorting/link_builder_spec.rb
- spec/support/metadata/current_user.rb
see issue https://github.com/wallaby-rails/wallaby/issues/167
> feat: user wallaby_user and authenticate_wallaby_user to avoid conflicts with current_user

- lib/authorizers/wallaby/cancancan_authorization_provider.rb
- lib/authorizers/wallaby/default_authorization_provider.rb
- lib/authorizers/wallaby/model_authorizer.rb
- lib/authorizers/wallaby/pundit_authorization_provider.rb
- lib/interfaces/wallaby/model_authorization_provider.rb
- lib/utils/wallaby/utils.rb
- spec/interfaces/wallaby/mode_spec.rb
- spec/interfaces/wallaby/model_authorization_provider_spec.rb
- spec/interfaces/wallaby/model_decorator_spec.rb
- spec/interfaces/wallaby/model_pagination_provider_spec.rb
- spec/interfaces/wallaby/model_service_provider_spec.rb
add options to authorizer and its providers to make it easier to test
> feat: add options to authorizer and its providers

- README.md
- lib/concerns/wallaby/baseable.rb
- lib/errors/wallaby/class_not_found.rb
- lib/wallaby/core.rb
- spec/concerns/wallaby/baseable_spec.rb
refactor guess_associated_class_of to allow suffix and attr_name so that it can be reused by other methods in the future
> chore: refactor guess_associated_class_of to allow suffix and attr_name

- CHANGELOG.md
- lib/wallaby/core/version.rb
> chore: ready for 0.2.2

- lib/concerns/wallaby/prefixable.rb
- lib/responders/wallaby/json_api_responder.rb
- lib/services/wallaby/type_renderer.rb
- spec/controllers/wallaby/resources_controller_spec.rb
Be able to fall back to form partial and metadata
> feat: be able to fall back to form partial and metadata

- lib/authorizers/wallaby/model_authorizer.rb
- lib/concerns/wallaby/authorizable.rb
- lib/concerns/wallaby/decoratable.rb
- lib/concerns/wallaby/engineable.rb
- lib/concerns/wallaby/paginatable.rb
- lib/concerns/wallaby/resources_concern.rb
- lib/concerns/wallaby/servicable.rb
- lib/concerns/wallaby/shared_helpers.rb
- lib/forms/wallaby/form_builder.rb
- lib/helpers/wallaby/application_helper.rb
- lib/helpers/wallaby/secure_helper.rb
- lib/interfaces/wallaby/model_authorization_provider.rb
- lib/responders/wallaby/resources_responder.rb
- lib/services/wallaby/engine_url_for.rb
- lib/wallaby/constants.rb
- lib/wallaby/logger.rb
> chore: update resource responder

- lib/concerns/wallaby/configurable.rb
- lib/concerns/wallaby/resources_concern.rb
- lib/helpers/wallaby/secure_helper.rb
- lib/wallaby/configuration/security.rb
- lib/wallaby/core.rb
- spec/features/controller_configuration/authentication_related_spec.rb
- spec/helpers/wallaby/secure_helper_spec.rb
- spec/support/type/helper.rb
- spec/support/type/view.rb
Deprecate security config and use controller's configuration instead.
> chore: deprecate security config

- Gemfile
- gemfiles/Gemfile.rails-4.2
- gemfiles/Gemfile.rails-5.0
- gemfiles/Gemfile.rails-5.1
- gemfiles/Gemfile.rails-5.2
- gemfiles/Gemfile.rails-6.0
- gemfiles/Gemfile.rails-master
- lib/generators/wallaby/engine/install/USAGE
- lib/generators/wallaby/engine/install/install_generator.rb
- lib/generators/wallaby/engine/install/templates/application_authorizer.rb.erb
- lib/generators/wallaby/engine/install/templates/application_controller.rb.erb
- lib/generators/wallaby/engine/install/templates/application_decorator.rb.erb
- lib/generators/wallaby/engine/install/templates/application_paginator.rb.erb
- lib/generators/wallaby/engine/install/templates/application_servicer.rb.erb
- lib/generators/wallaby/engine/install/templates/initializer.rb.erb
- spec/generators/wallaby/engine/install_generator_spec.rb
Move the generator from core and rename to wallaby:engine:install
> feat: add wallaby:engine:install generator

- lib/generators/wallaby/engine/authorizer/USAGE
- lib/generators/wallaby/engine/authorizer/authorizer_generator.rb
- lib/generators/wallaby/engine/authorizer/templates/authorizer.rb.erb
- lib/generators/wallaby/engine/controller/USAGE
- lib/generators/wallaby/engine/controller/controller_generator.rb
- lib/generators/wallaby/engine/controller/templates/controller.rb.erb
- lib/generators/wallaby/engine/decorator/USAGE
- lib/generators/wallaby/engine/decorator/decorator_generator.rb
- lib/generators/wallaby/engine/decorator/templates/decorator.rb.erb
- lib/generators/wallaby/engine/install/USAGE
- lib/generators/wallaby/engine/install/install_generator.rb
- lib/generators/wallaby/engine/paginator/USAGE
- lib/generators/wallaby/engine/paginator/paginator_generator.rb
- lib/generators/wallaby/engine/paginator/templates/paginator.rb.erb
- lib/generators/wallaby/engine/servicer/USAGE
- lib/generators/wallaby/engine/servicer/servicer_generator.rb
- lib/generators/wallaby/engine/servicer/templates/servicer.rb.erb
- spec/generators/wallaby/engine/authorizer_generator_spec.rb
- spec/generators/wallaby/engine/controller_generator_spec.rb
- spec/generators/wallaby/engine/decorator_generator_spec.rb
- spec/generators/wallaby/engine/install_generator_spec.rb
- spec/generators/wallaby/engine/paginator_generator_spec.rb
- spec/generators/wallaby/engine/servicer_generator_spec.rb
- spec/rails_helper.rb
> feat: add generators for controller/decorator/servicer/authorizer/paginator

- Gemfile
- gemfiles/Gemfile.rails-4.2
- gemfiles/Gemfile.rails-5.0
- gemfiles/Gemfile.rails-5.1
- gemfiles/Gemfile.rails-5.2
- gemfiles/Gemfile.rails-6.0
- gemfiles/Gemfile.rails-master
- lib/concerns/wallaby/prefixable.rb
- lib/services/wallaby/prefixes_builder.rb
- spec/concerns/wallaby/authorizable_spec.rb
- spec/concerns/wallaby/paginatable_spec.rb
- spec/concerns/wallaby/servicable_spec.rb
- spec/controllers/wallaby/resources_controller_spec.rb
- spec/dummy/app/controllers/application_controller.rb
- spec/dummy/app/controllers/base_controller.rb
- spec/dummy/app/controllers/blogs_controller.rb
- spec/dummy/app/controllers/items_controller.rb
- spec/dummy/config/routes.rb
- spec/features/include_as_module_spec.rb
- spec/features/theme_name_spec.rb
- spec/rails_helper.rb
- spec/routing/routes_spec.rb
- spec/services/wallaby/map_spec.rb
- spec/support/clear.rb
> feat: be able to include Wallaby::ResourcesConcern to get the same feature as Wallaby::ResourcesController

- lib/wallaby/engine.rb
- lib/wallaby/map.rb
- lib/wallaby/preloader.rb
see issue https://github.com/wallaby-rails/wallaby/issues/190
> feat: suppress preload until it's Wallaby related request

- lib/concerns/wallaby/baseable.rb
- spec/deprecation/deprecations_spec.rb
> chore: deprecate namespace attribute

- lib/utils/wallaby/module_utils.rb
- lib/wallaby/engine.rb
- spec/deprecation/deprecations_spec.rb
- spec/dummy/app/controllers/admin/order/items_controller.rb
- spec/utils/wallaby/module_utils_spec.rb
> chore: deprecate try_to

- lib/concerns/wallaby/authentication_concern.rb
- lib/concerns/wallaby/baseable.rb
- lib/helpers/wallaby/application_helper.rb
- lib/helpers/wallaby/links_helper.rb
- lib/services/wallaby/model_class_filter.rb
- lib/utils/wallaby/module_utils.rb
- lib/wallaby/configuration/models.rb
- lib/wallaby/guesser.rb
- spec/helpers/wallaby/application_helper_spec.rb
- spec/helpers/wallaby/links_helper_spec.rb
- spec/support/type/helper.rb
> chore: update url helpers and override form_for

- lib/concerns/wallaby/baseable.rb
- lib/helpers/wallaby/configuration_helper.rb
- lib/helpers/wallaby/resources_helper.rb
- lib/utils/wallaby/module_utils.rb
- lib/wallaby/configuration/mapping.rb
- lib/wallaby/configuration/metadata.rb
- lib/wallaby/configuration/models.rb
- lib/wallaby/configuration/pagination.rb
- lib/wallaby/configuration/security.rb
- lib/wallaby/configuration/sorting.rb
- lib/wallaby/map.rb
> chore: cleanup document for deprecated methods

- lib/generators/wallaby/engine/application_generator.rb
- lib/generators/wallaby/engine/authorizer/authorizer_generator.rb
- lib/generators/wallaby/engine/authorizer/templates/authorizer.rb.erb
- lib/generators/wallaby/engine/controller/controller_generator.rb
- lib/generators/wallaby/engine/controller/templates/controller.rb.erb
- lib/generators/wallaby/engine/decorator/decorator_generator.rb
- lib/generators/wallaby/engine/decorator/templates/decorator.rb.erb
- lib/generators/wallaby/engine/paginator/paginator_generator.rb
- lib/generators/wallaby/engine/paginator/templates/paginator.rb.erb
- lib/generators/wallaby/engine/servicer/servicer_generator.rb
- lib/generators/wallaby/engine/servicer/templates/servicer.rb.erb
> chore: refactor generators and move common codes into application generator

- lib/fields/wallaby/all_fields.rb
- lib/generators/wallaby/engine/install/install_generator.rb
- lib/helpers/wallaby/index_helper.rb
- lib/helpers/wallaby/secure_helper.rb
- lib/interfaces/wallaby/model_decorator.rb
- lib/wallaby/core.rb
1. update installer to accept true for include_partials
2. update link helpers
3. add ability to update metadata for all index/show/form fields
4. update security helper to make sure it takes the closest match
> chore: misc updates

- lib/concerns/wallaby/engineable.rb
- lib/helpers/wallaby/links_helper.rb
- lib/helpers/wallaby/resources_helper.rb
- lib/services/wallaby/engine_name_finder.rb
> chore: improve engine name finder

- .travis.yml
- lib/adaptors/wallaby/custom/model_decorator.rb
- lib/authorizers/wallaby/model_authorizer.rb
- lib/authorizers/wallaby/pundit_authorization_provider.rb
- lib/concerns/wallaby/configurable.rb
- lib/concerns/wallaby/fieldable.rb
- lib/decorators/wallaby/resource_decorator.rb
- lib/fields/wallaby/all_fields.rb
- lib/interfaces/wallaby/model_authorization_provider.rb
- lib/interfaces/wallaby/model_decorator.rb
- lib/interfaces/wallaby/model_finder.rb
- lib/services/wallaby/default_models_excluder.rb
- lib/services/wallaby/fields_regulator.rb
- lib/wallaby/core.rb
- spec/adaptors/wallaby/custom/model_decorator_spec.rb
- spec/concerns/wallaby/configurable_spec.rb
- spec/decorators/wallaby/resource_decorator_spec.rb
- spec/features/controller_configuration/authentication_related_spec.rb
- spec/helpers/wallaby/application_helper_spec.rb
- spec/lib/wallaby/all_fields_spec.rb
- spec/lib/wallaby/configuration_spec.rb
- spec/requests/custom_routes_and_controllers_spec.rb
- spec/services/wallaby/fields_regulator_spec.rb
> feat: allow dynamic x_fields/x_field_names/x_metadata_of/x_type_of/x_label_of

- Gemfile
- lib/concerns/wallaby/resourcable.rb
- lib/concerns/wallaby/resources_concern.rb
- lib/concerns/wallaby/urlable.rb
- lib/interfaces/wallaby/model_pagination_provider.rb
- lib/support/action_dispatch/routing/mapper.rb
- spec/adaptors/wallaby/custom/model_service_provider_spec.rb
- spec/deprecation/deprecations_spec.rb
- spec/dummy/app/models/invalid_model.rb
- spec/dummy/config/routes.rb
- spec/support/database_cleaner.rb
> feat: bring back the wresources

- lib/concerns/wallaby/fieldable.rb
- lib/wallaby/logger.rb
- spec/dummy/app/views/wallaby/resources/_form.html.erb
> chore: change to use Array.wrap

- .github/workflows/pr-build.yml
> chore: move CC_TEST_REPORTER_ID to repo secrets

- lib/routes/wallaby/engines/base_route.rb
- spec/helpers/wallaby/application_helper_spec.rb
> fix: resources name should check model_class before reading from recall

- lib/concerns/wallaby/fieldable.rb
- lib/interfaces/wallaby/model_decorator.rb
> feat: provide metadata options to hide fields

- lib/services/wallaby/sorting/hash_builder.rb
- lib/services/wallaby/sorting/next_builder.rb
- lib/services/wallaby/sorting/single_builder.rb
- spec/decorators/wallaby/resource_decorator_spec.rb
- spec/services/wallaby/sorting/hash_builder_spec.rb
> chore: refactor to move the to_str to HashBuilder

- .github/workflows/pr-build.yml
- spec/dummy/config/database.yml
> chore: update database names

- lib/services/wallaby/sorting/hash_builder.rb
- spec/dummy/config/database.yml
- spec/services/wallaby/sorting/hash_builder_spec.rb
> feat: support nulls first | last

- .github/workflows/pr-build.yml
- lib/routes/wallaby/resources_router.rb
- spec/utils/wallaby/locale_spec.rb
> Improve the error messages in lib/routes/wallaby/resources_router.rb

- lib/concerns/wallaby/baseable.rb
- lib/concerns/wallaby/prefixable.rb
- lib/decorators/wallaby/resource_decorator.rb
- lib/interfaces/wallaby/model_decorator.rb
> Fix issue related to primary key and improve prefixable

- lib/authorizers/wallaby/model_authorizer.rb
- lib/helpers/wallaby/base_helper.rb
- lib/utils/wallaby/locale.rb
> Update keyword syntax to support Ruby 3.0

- lib/wallaby/core/version.rb
> Update version to 0.2.8

- Gemfile
- spec/dummy/config/database.yml
- wallaby-core.gemspec
> Restrict dependency to below Rails 8.0

- lib/wallaby/engine.rb
- lib/wallaby/map.rb
- lib/wallaby/preloader.rb
> Suppress preload

- lib/wallaby/core/version.rb
> Bump version to 0.2.10

- lib/wallaby/core/version.rb
- lib/wallaby/engine.rb
- lib/wallaby/preloader.rb
Related to https://github.com/wallaby-rails/wallaby/issues/213
> Fix to clear preloading flag instead of using pending

- lib/concerns/wallaby/configurable.rb
- lib/concerns/wallaby/decoratable.rb
- lib/decorators/wallaby/resource_decorator.rb
- lib/forms/wallaby/form_builder.rb
- lib/helpers/wallaby/links_helper.rb
- lib/services/wallaby/map/mode_mapper.rb
- lib/wallaby/preloader.rb
- spec/decorators/wallaby/model_decorator_spec.rb
- spec/decorators/wallaby/resource_decorator_spec.rb
- spec/dummy/app/models/postcode.rb
- spec/dummy/app/models/profile.rb
- spec/helpers/wallaby/links_helper_spec.rb
- spec/support/shared_examples/attr.rb
> Add readonly
